# -*- coding: utf-8 -*-
"""Python analysis project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RBEofPG1Iz6od_jax0iVOnKKjAixSrse
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/Diwali Sales Data.csv", encoding="unicode_escape")

df

df.isna().sum()

len(df)

df=df.drop(columns=["Status","unnamed1"])

df.info()

df["Amount"]=df["Amount"].replace(np.nan,0)

df.isna().sum()

df[["Age","Orders","Amount"]].describe()

df.columns

"""**Gender**"""

num = sns.countplot(data=df, x="Gender" , hue="Gender")

for bars in num.containers:
    num.bar_label(bars)

plot=df.groupby(["Gender"], as_index=False)["Amount"].sum()

ax=sns.barplot(data=plot, x="Gender", y="Amount" , hue= "Gender")

"""***From the above graph we understand that there are more female buyers than male.***

**Age**
"""

sns.countplot(data=df, x="Age Group", hue="Gender" , palette=["red","yellow"])

df.groupby(["Age Group"], as_index=False)["Amount"].sum().sort_values(by="Amount", ascending=False)

"""***From the above analysis the top three age group with high purchasing rate are 26-35, 36-35, 18-25***

**Marital Status**
"""

sns.countplot(data=df, x="Marital_Status", hue="Gender")

pll=df.groupby(["Marital_Status","Gender"], as_index=False)["Amount"].sum().sort_values(by="Amount")
sns.set(rc={"figure.figsize":(6,4)})
sns.barplot(data=pll, x="Marital_Status", y="Amount", hue="Gender", palette=["orange","green"])

"""***From the above graph we understand that there are more married woman with high purchasing rate.***

**State**
"""

plot=df.groupby(["State","Gender"], as_index=False)["Orders"].sum().sort_values(by="Orders")

sns.set(rc={"figure.figsize":(25,5)})
sns.barplot(data=plot, x="State", y="Orders", hue="State")

"""**Top 10 States with high number of orders**"""

df.groupby(["State"], as_index=False)["Orders"].sum().sort_values(by="Orders", ascending= False).head(10)

"""***From the above graph we understand the top 5 states with high number of orders are Uttar Pradesh, Maharashtra, Karnataka, Delhi, Madhya Pradesh***

**Occupation**
"""

pl=sns.countplot(data=df, x="Occupation", hue="Occupation")
sns.set(rc={"figure.figsize":(25,10)})
for bars in pl.containers:
    pl.bar_label(bars)

pl=df.groupby(["Occupation"], as_index=False)["Amount"].sum().sort_values(by="Amount", ascending=False).head(10)
sns.barplot(data=pl, x="Occupation", y="Amount", hue="Occupation")

"""***From the above graph we understand that people from IT Sector, Healthcare, Aviation have high purchasing power***

**Product Category**
"""

pl=sns.countplot(data=df, x="Product_Category", hue="Product_Category")
sns.set(rc={"figure.figsize":(25,5)})
for bars in pl.containers:
    pl.bar_label(bars)

plt=df.groupby(["Product_Category"], as_index=False)["Orders"].sum().sort_values(by="Orders", ascending=False).head(10)
sns.barplot(data=plt, x="Product_Category", y="Orders", hue="Product_Category")

"""***From the above graph we understand that there are more orders from the product category of Clothing and Apparel, Food, Electronics & Gadgets***"""

df.groupby(["Age Group","State","Occupation","Product_Category","Gender"], as_index=False)["Amount"].sum().sort_values(by="Amount", ascending=False).head(10)

"""***Hence, we conclude that females from the age group of 26-35, state Uttar Pradesh, sector Aviation are more likely buy food.***"""